openapi: "3.0.0"
info:
  version: 1.0.0
  title: OpenAPI Specification
  description: Entities and methods for our Rest API.
paths:
  /ping:
    get:
      summary: Pings the system, measuring round-trip network time.
      operationId: ping
      tags:
        - system
      parameters:
        - name: timestamp
          in: query
          description: The timestamp that will be returned with the response.
          required: true
          default: 0
          schema:
            type: integer
            format: int64
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pong"
components:
  schemas:
    Pong:
      required:
        - timestamp
      properties:
        timestamp:
          type: integer
          format: int64
          default: 0
